<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_register_order_tests.MyTestCase-20230314183527" tests="27" file="test_register_order_tests.py" time="0.072" timestamp="2023-03-14T18:35:28" failures="1" errors="0" skipped="0">
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_12" time="0.016" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_13" time="0.003" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_14" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_15" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_18" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_2" time="0.003" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_20" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_21" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_24" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_25" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_3" time="0.000" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_4" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_5" time="0.003" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_8" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_9" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_1" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_10" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_11" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_17" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_19" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_23" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_6" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_7" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_LV_NV_16" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_LV_NV_26" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_VL_V_22" time="0.002" timestamp="2023-03-14T18:35:28"/>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_EXTRA1" time="0.003" timestamp="2023-03-14T18:35:28">
		<failure type="AssertionError" message="'e01521684a7f9535e9fa098a2b86565f' != '63b84176d87cb5bf8bd868b5ae9db1e6'
- e01521684a7f9535e9fa098a2b86565f
+ 63b84176d87cb5bf8bd868b5ae9db1e6
"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 379, in test_CE_NV_EXTRA1
    self.assertEqual(my_order_id, "63b84176d87cb5bf8bd868b5ae9db1e6")
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 873, in assertEqual
    assertion_func(first, second, msg=msg)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 1253, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 703, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: 'e01521684a7f9535e9fa098a2b86565f' != '63b84176d87cb5bf8bd868b5ae9db1e6'
- e01521684a7f9535e9fa098a2b86565f
+ 63b84176d87cb5bf8bd868b5ae9db1e6

]]></failure>
	</testcase>
</testsuite>
