<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_register_order_tests.MyTestCase-20230315181535" tests="36" file="test_register_order_tests.py" time="0.121" timestamp="2023-03-15T18:15:35" failures="0" errors="36" skipped="0">
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_12" time="0.021" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 166, in test_CE_NV_12
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_13" time="0.004" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 179, in test_CE_NV_13
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_14" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 193, in test_CE_NV_14
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_15" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 207, in test_CE_NV_15
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_18" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 249, in test_CE_NV_18
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_2" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 29, in test_CE_NV_2
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_20" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 276, in test_CE_NV_20
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_21" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 291, in test_CE_NV_21
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_24" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 331, in test_CE_NV_24
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_25" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 345, in test_CE_NV_25
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_3" time="0.001" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 43, in test_CE_NV_3
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_4" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 58, in test_CE_NV_4
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_5" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 72, in test_CE_NV_5
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_8" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 112, in test_CE_NV_8
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_NV_9" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 126, in test_CE_NV_9
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_1" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 15, in test_CE_V_1
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_10" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 140, in test_CE_V_10
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_11" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 153, in test_CE_V_11
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_17" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 236, in test_CE_V_17
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_19" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 263, in test_CE_V_19
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_23" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 318, in test_CE_V_23
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_29" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 401, in test_CE_V_29
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_30" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 414, in test_CE_V_30
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_31" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 427, in test_CE_V_31
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_32" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 440, in test_CE_V_32
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_33" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 454, in test_CE_V_33
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_34" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 468, in test_CE_V_34
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_6" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 86, in test_CE_V_6
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_CE_V_7" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 99, in test_CE_V_7
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_LV_NV_16" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 221, in test_LV_NV_16
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_LV_NV_26" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 359, in test_LV_NV_26
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_LV_NV_27" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 373, in test_LV_NV_27
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_LV_NV_28" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 387, in test_LV_NV_28
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_VE_V_36" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 495, in test_VE_V_36
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_VL_V_22" time="0.003" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 305, in test_VL_V_22
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
	<testcase classname="test_register_order_tests.MyTestCase" name="test_VL_V_35" time="0.002" timestamp="2023-03-15T18:15:35">
		<error type="AttributeError" message="module 'posixpath' has no attribute 'direname'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/lib/python3.11/site-packages/freezegun/api.py", line 809, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/unittest/python/test_register_order_tests.py", line 481, in test_VL_V_35
    my_manager = OrderManager()
    ^^^^^^^^^^^^^^^^^
  File "/Users/edu/PycharmProjects/G89.2023.T20.EG3/src/main/python/uc3m_logistics/order_manager.py", line 14, in __init__
    current_path = os.path.direname(__file__)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'direname'
]]></error>
	</testcase>
</testsuite>
